# FROM ubuntu:latest
FROM python:3.8.1
COPY api /exp/api
COPY ./requirements.txt /exp/requirements.txt
RUN pip3 install --no-cache-dir -r /exp/requirements.txt
EXPOSE 5000
WORKDIR /exp/api
CMD ["python", "-m", "flask", "run"]